name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: PR Title Checker
        uses: AmayaAngel/github-actions-pr-title-checker@v2.2.2
        with:
          regex: '^CLOUD-\d+'
          error_message: 'Pull request title does not start with `CLOUD-` followed by numbers. Please update the title.'
